### ISSUE TITLE
Cannot load kernel without a valid FS

### ISSUE THREAD

**Issue by dmenezesgabriel** [DerThorsten/xeus-javascript#40]
Trying to run Jupyterlite latest version with `xeus-javascript kernel` and got the error: `Cannot load kernel without a valid FS`.

![Image](https://github.com/user-attachments/assets/4497284e-7356-4052-8390-e9437d8e1370)

- **build-environment.yml**:

```yaml
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server=2.16.0
  - jupyterlite-core=0.6.2
  - jupyterlite-xeus=4.0.3
  - jupyterlite-javascript-kernel=0.3.0
  - jupyterlite-pyodide-kernel=0.6.1
```

- **environment.yml**:

```yaml
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - xeus-sqlite
  - xeus-javascript=0.4.0
  - scikit-learn=1.1.3
  - scipy=1.11.1
  - pandas=2.2.3
  - numpy=1.25.2
  - matplotlib=3.9.4
  - plotly=6.1.2
  - ipywidgets=8.1.7
  - rich=14.0.0
```

**Comment by DerThorsten** [comment]
You just need to update a few things: Here is a [repo](https://github.com/DerThorsten/xeus-js-demo) with a working [xeus-javascript deployment ](https://derthorsten.github.io/xeus-js-demo/lab/index.html)I created a few minutes ago.

Your build environment uses somewhat outdated / not needed packages its enough to have 
```Yaml
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.6
  - jupyterlite-xeus >=4
```


the wasm environment should look similar to:
```Yaml
name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-javascript
```

Note that we moved from `https://repo.mamba.pm/emscripten-forge` to `https://repo.prefix.dev/emscripten-forge-dev`
